# Generated by Django 2.0.8 on 2018-09-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180907_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptitudescore',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='apt',
        ),
        migrations.DeleteModel(
            name='AptitudeScore',
        ),
    ]
