# Generated by Django 2.0.8 on 2018-09-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180908_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='creator',
            new_name='joiner',
        ),
    ]
