# Generated by Django 2.0.8 on 2018-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180908_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(default=0),
        ),
    ]
