# Generated by Django 2.0.8 on 2018-10-26 09:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180915_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='apt_score',
        ),
        migrations.AddField(
            model_name='join',
            name='score_apt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='apt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
